id: P010416
initial_creation_type: ocr
source_metadata:
  id: bdr:W20434
  title: གཉན་ཐོག་བྱམས་པ་གླིང་གི་ལོ་རྒྱུས
  author: ''
  volumes:
    a467b46341e643c58dfb7fdb9aa7b58e:
      image_group_id: I5827
      title: ''
      volume_number: 1
      total_pages: 411
      base_file: v001.txt
