id: IB4CB16B3
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T04:28:15+00:00'
last_modified: '2022-06-08T13:25:49.942944+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W20434
  title: གཉན་ཐོག་བྱམས་པ་གླིང་གི་ལོ་རྒྱུས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    CAC5:
      image_group_id: I5827
      title: ''
      total_pages: 411
      order: 1
      base_file: CAC5.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
